# Generated by Django 3.1.5 on 2021-01-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('chat_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('is_done', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('m_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
