# Generated by Django 3.1.5 on 2021-02-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('chat_id', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('owner_open_id', models.CharField(max_length=200)),
                ('owner_user_id', models.CharField(max_length=200)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('m_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
