# Generated by Django 3.1.5 on 2021-02-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feishu', '0002_groupinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinfo',
            old_name='img',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='groupinfo',
            old_name='desc',
            new_name='description',
        ),
    ]
